### ISSUE TITLE
README talks about non-existent directory

### ISSUE THREAD

**Issue by juampi** [saasbook/hw-bdd-cucumber#2]
The README says:

> The app code in __public/app__ contains a "canonical" solution to the Rails Intro homework against which to write your scenarios, and the necessary scaffolding for the first couple of scenarios.

> Create a repo and start by pushing this skeleton to it.

However, there's no __public/app__ directory. It could be referring to __rottenpotatoes/app__, but if that's the case, what about the other directories, like __rottenpotatoes/features__? I believe it's not clear what the skeleton we're supposed to use is.

**Comment by tansaku** [comment]
Hi @juampi thanks for flagging that - I have updated the READMEs - please let me know if that clears things up

**Comment by bill-auger** [comment]
this is fixed and stale
